on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake pkg-config check libsubunit-dev cppcheck doxygen valgrind
#    - name: cppcheck
#      run: cppcheck --check-config --force --enable=warning,missingInclude --error-exitcode=1 .
    - name: build
      run: |
        mkdir build
        cd build
        cmake -DBUILD_HELPERS_DOCUMENTATION=on ..
        make package doc
        sudo make install
        cd ..
        make
        make clean check
